apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: auction-tracker
    component: backend
spec:
  type: ClusterIP
  selector:
    app: auction-tracker
    component: backend
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  - name: debug
    port: 9229
    targetPort: debug
    protocol: TCP