# Development override configuration
# This file is automatically loaded by docker-compose in development

services:
  nellis-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for hot-reloading
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
      # Prevent node_modules from being overwritten by mount
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: nodemon src/index.js