services:
  nellis-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nellis-auction-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AUTH_TOKEN=${AUTH_TOKEN:-dev-token}
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - nellis-network

  # Optional: Add Redis for session/cache management in the future
  # redis:
  #   image: redis:7-alpine
  #   container_name: nellis-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - nellis-network

networks:
  nellis-network:
    driver: bridge

# volumes:
#   redis-data: