# Production overrides
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# Or with env file: docker-compose --env-file .env.production up -d

services:
  backend:
    build:
      target: production
    ports:
      - "3000:3000"  # No debug port in production
    environment:
      - NODE_ENV=production
      - DEBUG=  # Disable debug logging
    volumes:
      # Only logs volume in production (no source code mounting)
      - ./backend/logs:/app/logs

  dashboard:
    build:
      target: production
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes: []  # No volumes in production