# Production configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  nellis-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production