#!/bin/bash

echo "Chrome/Puppeteer Dependencies Installation Script"
echo "================================================"
echo ""
echo "This script installs the required dependencies for running Puppeteer with Chrome."
echo "You'll need to run this with sudo privileges."
echo ""
echo "Run the following command:"
echo ""
echo "sudo apt-get update && sudo apt-get install -y \\"
echo "    ca-certificates \\"
echo "    fonts-liberation \\"
echo "    libasound2 \\"
echo "    libatk-bridge2.0-0 \\"
echo "    libatk1.0-0 \\"
echo "    libc6 \\"
echo "    libcairo2 \\"
echo "    libcups2 \\"
echo "    libdbus-1-3 \\"
echo "    libexpat1 \\"
echo "    libfontconfig1 \\"
echo "    libgbm1 \\"
echo "    libgcc1 \\"
echo "    libglib2.0-0 \\"
echo "    libgtk-3-0 \\"
echo "    libnspr4 \\"
echo "    libnss3 \\"
echo "    libpango-1.0-0 \\"
echo "    libpangocairo-1.0-0 \\"
echo "    libstdc++6 \\"
echo "    libx11-6 \\"
echo "    libx11-xcb1 \\"
echo "    libxcb1 \\"
echo "    libxcomposite1 \\"
echo "    libxcursor1 \\"
echo "    libxdamage1 \\"
echo "    libxext6 \\"
echo "    libxfixes3 \\"
echo "    libxi6 \\"
echo "    libxrandr2 \\"
echo "    libxrender1 \\"
echo "    libxss1 \\"
echo "    libxtst6 \\"
echo "    lsb-release \\"
echo "    wget \\"
echo "    xdg-utils"
echo ""
echo "Alternatively, for a minimal headless setup, you can try:"
echo "sudo apt-get install -y chromium-browser"