apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources
resources:
- namespace.yaml
- ../../base
- patches/pdb-backend.yaml
- patches/pdb-dashboard.yaml
- patches/network-policy.yaml
- patches/hpa-backend.yaml
- patches/hpa-dashboard.yaml

# Production namespace
namespace: auction-tracker

# Production-specific patches
patches:
# Backend patches - increase replicas and resources
- target:
    kind: Deployment
    name: backend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - backend
              topologyKey: kubernetes.io/hostname
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "2"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "500m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"

# Dashboard patches - increase replicas
- target:
    kind: Deployment
    name: dashboard
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - dashboard
              topologyKey: kubernetes.io/hostname

# Redis patches - production configuration
- target:
    kind: StatefulSet
    name: redis
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args
      value:
      - --requirepass
      - $(REDIS_PASSWORD)
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
      value: "10Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"

# ConfigMap replacements
configMapGenerator:
- name: backend-config
  behavior: merge
  literals:
  - LOG_LEVEL=info
  - ALLOWED_ORIGINS=https://auction-tracker.example.com
  - RATE_LIMIT_WINDOW_MS=60000
  - RATE_LIMIT_MAX_REQUESTS=1000
  - HELMET_ENABLED=true
  - ENABLE_METRICS=true

- name: dashboard-config
  behavior: merge
  literals:
  - EXTERNAL_BACKEND_URL=https://api.auction-tracker.example.com
  - EXTERNAL_WS_URL=wss://api.auction-tracker.example.com
  - ENABLE_ANALYTICS=true

- name: redis-config
  behavior: merge
  literals:
  - REDIS_MAXMEMORY=512mb
  - REDIS_SAVE="900 1 300 10 60 10000"

# Secret references (secrets created separately)
secretGenerator:
- name: backend-secrets
  files:
  - secrets/auth-token
  - secrets/encryption-secret

- name: redis-secrets
  files:
  - secrets/redis-password

# TLS certificate
- name: auction-tracker-tls
  files:
  - secrets/tls.crt
  - secrets/tls.key
  type: kubernetes.io/tls

# Patches for Gateway
patches:
- path: gateway-patch.yaml


# Production-specific labels
labels:
- pairs:
    environment: production