apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include all components
resources:
- backend
- dashboard
- redis
- gateway

# Namespace is set in overlays

# Common labels applied to all resources
labels:
- pairs:
    app: auction-tracker
    managed-by: kustomize

# Common annotations
commonAnnotations:
  version: "1.0.0"